### ISSUE TITLE
Chrome insecure Cert

### ISSUE THREAD

**Issue by SubZero1993** [si9int/m2p.py#1]
If the server uses an insecure certificate the screenshot is just white/empty. Tried to accomplish the problem with adding "--ignore-certificate-errors" to the argument list, but didn't help.. probably just got ignored by chrome

**Comment by si9int** [comment]
Are you using the current version?
I've fixed the issue in https://github.com/si9int/m2p.py/commit/8a2f96eec366c4788cd4808b383cc25afb00223e

"--ignore-certificate-errors" isn't working for the chromium driver in headless-mode.

**Comment by SubZero1993** [comment]
Oh well.. you're right! My Git messed something up on the latest pull, my fault! Sry about that :)
